FROM gradle:9.7.1-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle --no-daemon bootJar

FROM eclipse-temurin:21-jre
WORKDIR /app
ENV PORT=80
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 80
CMD ["/opt/java/openjdk/bin/java", "-XX:TieredStopAtLevel=1", "-jar", "app.jar"]
